//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLibrary.UI.Assets {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GameLibrary.UI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        public static string FirstRunExplanation {
            get {
                return ResourceManager.GetString("FirstRunExplanation", resourceCulture);
            }
        }

        public static string AboutLicenseHeader {
            get {
                return ResourceManager.GetString("AboutLicenseHeader", resourceCulture);
            }
        }

        public static string AboutFontAwesomeLicenseHeader {
            get {
                return ResourceManager.GetString("AboutFontAwesomeLicenseHeader", resourceCulture);
            }
        }

        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }

        public static string FirstRunInstructions {
            get {
                return ResourceManager.GetString("FirstRunInstructions", resourceCulture);
            }
        }

        public static string SettingsIgdbClientIdLabel {
            get {
                return ResourceManager.GetString("SettingsIgdbClientIdLabel", resourceCulture);
            }
        }

        public static string SettingsIgdbClientSecretLabel {
            get {
                return ResourceManager.GetString("SettingsIgdbClientSecretLabel", resourceCulture);
            }
        }

        public static string ButtonLabelSave {
            get {
                return ResourceManager.GetString("ButtonLabelSave", resourceCulture);
            }
        }

        public static string ButtonLabelBack {
            get {
                return ResourceManager.GetString("ButtonLabelBack", resourceCulture);
            }
        }

        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
    }
}
